version: '3.9'
services:
  hls_v2:
    container_name: ioc-hls_v2
    build: .
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - /usr/data/repo-HLS:/usr/data/repo-HLS
    stdin_open: true
    tty: true
    entrypoint: /usr/scripts/run-ioc-HLS.sh
    restart: unless-stopped
