version: '3.9'
services:
  hls:
    container_name: ioc-hls
    build: .
    network_mode: host
    devices:
      - "/dev/ttyUSB1:/dev/ttyUSB1"
    volumes:
      - /usr/data/repo-HLS:/usr/data/repo-HLS
    stdin_open: true
    tty: true
    entrypoint: /usr/scripts/run-ioc-HLS.sh
    restart: unless-stopped
