version: '3.9'
services:
  concrete:
    container_name: ioc-concrete_v2
    build:
      context: .
      args:
        - EPICS_BASE=/usr/local/epics/base
    network_mode: host
    volumes:
      - /usr/data/ftp-concrete:/usr/data/ftp-concrete
      - /usr/data/repo-concrete:/usr/data/repo-concrete
    stdin_open: true
    tty: true
    restart: unless-stopped
    #entrypoint: /usr/scripts/run-ioc.sh
