version: '3.9'
services:
  concrete:
    container_name: ftp-concrete_v2
    build: .
    network_mode: host
    volumes:
      - /usr/data/repo-concrete:/usr/data/repo-concrete
      - /usr/data/ftp-concrete:/usr/data/ftp-concrete
    stdin_open: true
    tty: true
    restart: unless-stopped
